name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
          coverage: none

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

  migrations:
    runs-on: ubuntu-latest
    needs: setup

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
          coverage: none

      - name: Run migrations
        id: run_migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: password
        run: |
          php artisan migrate --force || echo "migrations_failed=true" >> $GITHUB_ENV

  tests:
    runs-on: ubuntu-latest
    needs: migrations

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
          coverage: none

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        id: run_tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: password
        run: |
          php artisan test || echo "tests_failed=true" >> $GITHUB_ENV

  code_style:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
          coverage: none

      - name: Run Pint (Code Style)
        id: run_pint
        run: |
          vendor/bin/pint --test || echo "pint_failed=true" >> $GITHUB_ENV

  static_analysis:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
          coverage: none

      - name: Run PHPStan (Static Analysis)
        id: run_phpstan
        run: |
          vendor/bin/phpstan analyse || echo "phpstan_failed=true" >> $GITHUB_ENV

  refactoring:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, xml, intl, json
          coverage: none

      - name: Run Rector (Automated Refactoring)
        id: run_rector
        run: |
          vendor/bin/rector process --dry-run || echo "rector_failed=true" >> $GITHUB_ENV

  fail_job_if_any_step_failed:
    runs-on: ubuntu-latest
    needs: [migrations, tests, code_style, static_analysis, refactoring]

    steps:
      - name: Check for failures and fail job if any step failed
        run: |
          if [[ "${{ env.migrations_failed }}" == "true" ]] || \
             [[ "${{ env.tests_failed }}" == "true" ]] || \
             [[ "${{ env.pint_failed }}" == "true" ]] || \
             [[ "${{ env.phpstan_failed }}" == "true" ]] || \
             [[ "${{ env.rector_failed }}" == "true" ]]; then
            exit 1
          fi
