name: Test Migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [mysql, pgsql, sqlite]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: app_test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=password" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U root -d app_test" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo, pdo_mysql, pdo_pgsql, mbstring, xml, intl, json
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --no-interaction

      - name: Copy .env.testing file
        run: |
          cp .env.testing.production .env.testing
          php -r "file_exists('.env.testing') || copy('.env.testing.production', '.env.testing');"

      - name: Set up database configuration for .env.testing
        run: |
          if [ "${{ matrix.database }}" == "mysql" ]; then
            echo "DB_CONNECTION=mysql" >> .env.testing
            echo "DB_HOST=127.0.0.1" >> .env.testing
            echo "DB_PORT=3306" >> .env.testing
            echo "DB_DATABASE=app_test" >> .env.testing
            echo "DB_USERNAME=root" >> .env.testing
            echo "DB_PASSWORD=password" >> .env.testing
          elif [ "${{ matrix.database }}" == "pgsql" ]; then
            echo "DB_CONNECTION=pgsql" >> .env.testing
            echo "DB_HOST=127.0.0.1" >> .env.testing
            echo "DB_PORT=5432" >> .env.testing
            echo "DB_DATABASE=app_test" >> .env.testing
            echo "DB_USERNAME=root" >> .env.testing
            echo "DB_PASSWORD=password" >> .env.testing
          else
            echo "DB_CONNECTION=sqlite" >> .env.testing
            echo "DB_DATABASE=/tmp/database.sqlite" >> .env.testing
            touch /tmp/database.sqlite
          fi

      - name: Generate application key
        run: php artisan key:generate --env=testing

      - name: Run migrations
        run: php artisan migrate --force --env=testing

      - name: Run tests
        run: php artisan test --env=testing